### ISSUE TITLE
Error during algolia indexing

### ISSUE THREAD

**Issue by zhoubin-me** [LouisBarranqueiro/hexo-algoliasearch#124]
### Description
During running:
```hexo algolia```

It throws this error:
```
INFO  2 files generated in 6.62 s
INFO  Clearing index on Algolia...
INFO  Error has occurred during clearing index : TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "x-algolia-application-id"
FATAL {
  err: TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "x-algolia-application-id"
      at ClientRequest.setHeader (_http_outgoing.js:561:3)
      at new ClientRequest (_http_client.js:251:14)
      at Object.request (https.js:313:10)
      at /Users/bzhou/Workspace/zhoubin.me/node_modules/@algolia/requester-node-http/dist/requester-node-http.cjs.js:27:72
      at new Promise (<anonymous>)
      at Object.send (/Users/bzhou/Workspace/zhoubin.me/node_modules/@algolia/requester-node-http/dist/requester-node-http.cjs.js:16:20)
      at retry (/Users/bzhou/Workspace/zhoubin.me/node_modules/@algolia/transporter/dist/transporter.cjs.js:215:38)
      at /Users/bzhou/Workspace/zhoubin.me/node_modules/@algolia/transporter/dist/transporter.cjs.js:228:16
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    code: 'ERR_HTTP_INVALID_HEADER_VALUE'
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```

### Environment
 - Windows 10
 - nodejs v14.15.3
 - hexo 5.4.0
 - hexo-cli 4.2.0

### Plugin configuration
```
  applicationID: xxx
  apiKey: xxx
  adminApiKey: xxx
  chunkSize: 5000
  indexName: "dev_ZHOUBIN"
  fields:
    - content:strip:truncate,0,500
    - excerpt:strip
    - gallery
    - permalink
    - photos
    - slug
    - tags
    - title
```

### Additional information
- [ ] I can fix this bug
