### ISSUE TITLE
Can not collected post

### ISSUE THREAD

**Issue by heowc** [LouisBarranqueiro/hexo-algoliasearch#126]
### Description

```
INFO  164 files generated in 1.02 s
INFO  0 posts collected
INFO  Clearing index on Algolia...
INFO  Index cleared
INFO  Indexing posts on Algolia...
INFO  Indexation done. 0 posts indexed.
```

### Expected behavior

We should be able to collect posts normally and create indexes

### Environment
 - **OS (name & version)** : MacOS
 - **Node version**:  v14.16.1
 - **Hexo version**: 6.0
 - **Hexo-cli version**: 4.3

### Plugin configuration

```yml
algolia:
  appId: "xxx"
  apiKey: "xxx"
  adminApiKey: "xxx"
  chunkSize: 5000
  indexName: "heowc.github.io"
  fields:
    - tags
    - path
    - title
    - permalink
```

### Additional information
- [ ] I can fix this bug
