### ISSUE TITLE
The search results link not correct!

### ISSUE THREAD

**Issue by yuan199696** [LouisBarranqueiro/hexo-algoliasearch#129]
![image](https://user-images.githubusercontent.com/32838333/147478249-92d99dc5-c3f9-48c7-b753-66a65b3a67e5.png)

there is my config:
```yml
title: 
subtitle: 
description: 'love and peace'
keywords: Java
author: fanfanfan
language:
  - zh-CN
  - en
timezone: 'Asia/Shanghai'

url: https://baiyezi.vip
root: /
permalink: :title/ #:year/:month/:day/:title/
permalink_defaults:

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md
default_layout: post
titlecase: false 
external_link:
  enable: true 
  field: site 
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false

index_generator:
  path: ''
  per_page: 10
  order_by: -date

default_category: uncategorized
category_map:
  Java: java
  大big-data: big-data
  front: front
tag_map:

meta_generator: true
updated_option: 'mtime'

theme: shoka

algolia:
  appId: *** #Your appId
  apiKey: *** #Your apiKey
  adminApiKey: *** #Your adminApiKey
  chunkSize: 5000
  indexName: "fanfanfan"
  fields:
    - title
    - tags
    - slug
    - excerpt
    - excerpt:strip
    - photos
    - permalink
```
so ,why the search results link is not correct?
 i try to both add "path" and permalink to the fields,the search results link like "https://title",
and when i just add "permalink" to the fields,the results link like "https://url/undifiend".
what should i do?
