### ISSUE TITLE
AlgoliaSearchError

### ISSUE THREAD

**Issue by zouyaoji** [LouisBarranqueiro/hexo-algoliasearch#18]
hi, this is my error logs, The AlgoliaSearchError.
{
  "message": "Record at the position 0 objectID=cje9dg0110004br5nhvssgcb9 is too big size=13888 bytes. Contact us if you need an extended quota",
  "position": 0,
  "objectID": "cje9dg0110004br5nhvssgcb9",
  "status": 400
}

I have try decrease size of chunks , but it is not pass~
can you help me?
Best Regards!

**Comment by LouisBarranqueiro** [comment]
👋  @zouyaoji, the size of chunk does not matter. In your case, Algolia wants you to reduce the size of  data you index. I guess, you tried to index entire body of your posts or something else really big. If that's the case, I recommend you to index excerpts instead of bodies. If not, please add your hexo-algoliasearch configuration file here.

**Comment by zouyaoji** [comment]
@LouisBarranqueiro 
Thank you for yous reply. 
but, How to index excerpts instead of bodies?

this is my hexo-algoliasearch configuration?

```yml
algolia: 
  chunkSize: 5000
  fields:
    - title
    - tags
    - categories
    - excerpt:strip
    - content:strip
    - slug
    - permalink
    - path
```
```yml
algolia_search:
  enable: true
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"
```

[This is my hexoblog](https://github.com/zouyaoji/zouyaoji.github.io/tree/hexo)

Best Regards!
