### ISSUE TITLE
Process out of memory

### ISSUE THREAD

**Issue by aerohub** [LouisBarranqueiro/hexo-algoliasearch#2]
Hey, @LouisBarranqueiro. Thank you for great plugin! It could save my project's search, but I get an error again and again. I think the problem is not with your plugin, but with my environment. May be you know what is the matter?

### My configuration

 - **Operating system with version** : Windows_NT 6.1.7601 win32 x64
 - **Node version** : 4.4.5
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : developers 1.9.0
 

`project's _config.yml`
```
algolia:
  appId: "xxxxxxxxxx"
  apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxx"
  adminApiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  chunkSize: 5000
  indexName: "xxxxxxxxxxxxxxxxxxx"
  fields:
    - title
    - date
    - permalink
    - tags
    - categories
    - excerpt
    - excerpt:strip
```
### Actual behavior
```
Z:\project>hexo algolia
INFO  Collecting posts...
INFO  Start processing
INFO  Files loaded in 51 s

<--- Last few GCs --->

  137253 ms: Mark-sweep 1696.2 (1786.6) -> 1684.6 (1786.6) MB, 38.6 / 0 ms (+ 25
5.0 ms in 20 steps since start of marking, biggest step 115.0 ms) [allocation fa
ilure] [GC in old space requested].
  137557 ms: Mark-sweep 1684.6 (1786.6) -> 1693.9 (1777.6) MB, 290.7 / 0 ms [las
t resort gc].
  137831 ms: Mark-sweep 1693.9 (1777.6) -> 1690.7 (1771.6) MB, 281.7 / 0 ms [las
t resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000135CB1B4639 <JS Object>
    1: Join(aka Join) [native array.js:133] [pc=0000018D33813807] (this=00000135
CB1041B9 <undefined>,o=000002073AAFAD79 <JS Array[33]>,v=33,C=00000135CB104291 <
String[0]: >,B=00000135CB195299 <JS Function ConvertToString (SharedFunctionInfo
 00000135CB14A031)>)
    2: InnerArrayJoin(aka InnerArrayJoin) [native array.js:331] [pc=0000018D3391
EDAA] (this=00000135CB1041B9 <undefined>,C=00000135CB1...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```
