### ISSUE TITLE
How to index records of multiple Hexo layout types?

### ISSUE THREAD

**Issue by ifyour** [LouisBarranqueiro/hexo-algoliasearch#20]
My Hexo site has multiple layout types, and it seems that this plugin only index `post` type.

Is there a configurable option?

Like this:
```yml
algolia
  ...
  layouts: 
    - post
    - page
    - doc
```

### `_config.yml`
```yml
algolia:
  appId: 3XQ5CPDDMK
  apiKey: --hidden--
  adminApiKey: --hidden--
  chunkSize: 5000
  indexName: prod_blog
  fields:
    - title
    - tags
    - layout
    - from
    - permalink
    - excerpt:strip
    - content:strip:truncate,200,1600
```
