### ISSUE TITLE
problem with Algolia

### ISSUE THREAD

**Issue by HIKALU-Z** [LouisBarranqueiro/hexo-algoliasearch#4]
i like  your theme very much and now i have some error
after I install algolia
and set the theme's `config.yml` as yours
```
algolia:
  appId: "Z7A3XW4R2I"
  apiKey: "12db1ad54372045549ef465881c17e743"
  adminApiKey: "40321c7c207e7f73b63a19aa24c4761b"
  chunkSize: 5000
  indexName: "tranquilpeak"
  fields:
    - title
    - date
    - permalink
    - thumbnailImageUrl
    - tags
    - categories
    - excerpt
    - excerpt:strip
```

but when i use `hexo algolia`
it said  ` 'Cannot read property 'fields' of undefined'`
did i do something wrong?
